<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "community_fees".
 *
 * @property int $id 文章ID
 * @property string $title 标题
 * @property int $author 作者
 * @property int $community_id 小区
 * @property string $content 内容
 * @property int $create_time 创建时间
 * @property int $update_time 更新时间
 * @property string $version 版本号
 * @property int $status 状态，0=> 禁用，1=>启用, 2=>审核
 * @property string $property 备注
 *
 * @property CommunityBasic $community
 * @property SysUser $author0
 */
class CommunityFees extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'community_fees';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'community_id', 'content', 'version', 'status'], 'required'],
            [['author', 'community_id', 'status'], 'integer'],
            [['title'], 'string', 'max' => 50],
            [['content'], 'string', 'max' => 2000],
            [['version'], 'string', 'max' => 32],
            [['property'], 'string', 'max' => 64],
            [['community_id'], 'exist', 'skipOnError' => true, 'targetClass' => Community::className(), 'targetAttribute' => ['community_id' => 'community_id']],
            [['author'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['author' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => '标题',
            'author' => '作者',
            'content' => '内容',
            'create_time' => '创建时间',
            'update_time' => '修改时间',
            'community_id' => '小区',
            'version' => '版本号',
            'status' => '状态',
            'property' => '备注',
        ];
    }

    static function arr($one)
    {
        $status = [0 => '禁用', 1 => '启用', 2 => '审核'];

        $result = [ 'status' => $status];
        return $result[$one];
    }

    function beforeSave($insert)
    {
        parent::beforeSave($insert); //父级操作
        if($insert){ //判断是否是插入新记录
            $this->update_time = time();
            $this->create_time = time();
            $this->author = Yii::$app->user->id;
        }else{
            $this->update_time = time();
            $this->create_time = strtotime($this->create_time);
        }
        return true; //返回操作成功
    }

    //查询字段转换
    function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        $this->create_time = date('Y-m-d H:s:i', $this->create_time);
        $this->update_time = date('Y-m-d H:s:i', $this->update_time);
    }

    function getC() //截取字符串
    {
        $content = strip_tags($this->content);
        $con = mb_strlen($content);

        return mb_substr($content,0,10,'utf-8').(($con>30)?'...':'');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAu()
    {
        return $this->hasOne(User::className(), ['id' => 'author']);
    }

    public function getCommunity()
    {
        return $this->hasOne(Community::className(), ['community_id' => 'community_id']);
    }
}