<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "information".
 *
 * @property int $remind_id （序号）
 * @property int $community （房号 => 小区）
 * @property string $detail （详情）
 * @property int $times （提醒次数）
 * @property int $reading （是否已读，0=未读）
 * @property string $target （提醒对象）
 * @property string $ticket_number （投诉序号）
 * @property string $remind_time （提醒时间）
 * @property string $property （备注）
 *
 * @property CommunityBasic $community0
 */
class Information extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'information';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['community', 'times', 'type', 'remind_time'], 'required'],
            [['community', 'times', 'reading', 'remind_time', 'target'], 'integer'],
            [['detail', 'property'], 'string', 'max' => 50],
            [['ticket_number'], 'string', 'max' => 128],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'remind_id' => '序号',
            'community' => '小区',
            'detail' => '详情',
            'times' => '提醒次数',
            'reading' => '已读',
            'target' => '接收者',
            'type' => '类型',
            'ticket_number' => '订单编号',
            'remind_time' => '提醒时间',
            'property' => '备注',
        ];
    }

    //添加商品审核
    static function add($store, $message, $type, $number)
    {
        $model = new Information(); //实例化数据

        $model->community = $store;
        $model->target = '';
        $model->detail = $message;
        $model->times = '0';
        $model->reading = 0;
        $model->ticket_number = $number;
        $model->remind_time = time();
        $model->type = $type;

        $resutl = $model->save(); //保存
        if($resutl){
            return true;
        }
        return false;
    }

    //转换时间
    function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        $this->remind_time = date('Y-m-d H-i-s', $this->remind_time);
    }

    //截取字符串
    public function getE()
    {
        $tmpStr = strip_tags($this->ticket_number);
        $tmpLen = mb_strlen($tmpStr);

        return mb_substr($tmpStr,0,20,'utf-8').(($tmpLen>20)?'...':'');
    }

    public function getD()
    {
        $tmpStr = strip_tags($this->detail);
        $tmpLen = mb_strlen($tmpStr);

        return mb_substr($tmpStr,0,20,'utf-8').(($tmpLen>20)?'...':'');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getC()
    {
        return $this->hasOne(Community::className(), ['community_id' => 'community']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTarget0()
    {
        return $this->hasOne(User::className(), ['id' => 'target']);
    }
}
