<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "product_basic".
 *
 * @property int $product_id （产品ID）
 * @property int $store_id （关联商店ID）
 * @property string $product_name （商品名称）
 * @property string $product_subhead （商品副标题）
 * @property string $product_taxonomy （商品系列）
 * @property int $brand_id （品牌ID）
 * @property string $market_price （市场价格）
 * @property string $product_image （商品缩略图）
 * @property string $product_introduction （商品介绍）
 * @property string $product_sale （最大优惠金额）
 * @property string $product_accumulate （最大积分低现金额）
 * @property int $product_status （产品状态，1-上架，2-下架）
 * @property int $create_time （创建时间）
 * @property int $update_time （修改时间）
 *
 * @property StoreBasic $store
 * @property ProductProperty[] $productProperties
 * @property ShoppingCart[] $shoppingCarts
 * @property UserAccount[] $accounts
 */
class Product extends \yii\db\ActiveRecord
{
    public $name;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'product_basic';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['store_id', 'product_name', 'product_subhead', 'product_taxonomy', 'brand_id', 'market_price', 'product_image', 'product_introduction', 'product_sale', 'product_accumulate', 'product_status'], 'required'],
            [['store_id', 'brand_id', 'product_status', 'reading'], 'integer'],
            [['market_price', 'product_sale', 'product_accumulate'], 'number'],
            [['product_name', 'product_subhead', 'product_taxonomy'], 'string', 'max' => 64],
            [['product_image'], 'string', 'max' => 300],
            [['product_introduction'], 'string', 'max' => 20000],
            [['store_id', 'product_name'], 'unique', 'targetAttribute' => ['store_id', 'product_name']],
            [['store_id'], 'exist', 'skipOnError' => true, 'targetClass' => Store::className(), 'targetAttribute' => ['store_id' => 'store_id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'product_id' => 'Product ID',
            'store_id' => '商城',
            'product_name' => '名称',
            'product_subhead' => '标题',
            'brand_id' => '品牌',
            'product_taxonomy' => '商品系列',
            'market_price' => '市场价',
            'product_image' => '缩略图',
            'product_introduction' => '详情',
            'product_sale' => '优惠券金额',
            'product_accumulate' => '积分优惠',
            'product_status' => '状态',
            'reading' => '点击量',
            'create_time' => '创建时间',
            'update_time' => '更新时间',
            'name' => '分类'
        ];
    }

    function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        $this->create_time = date('Y-m-d H:i:s', $this->create_time);
        $this->update_time = date('Y-m-d H:i:s', $this->update_time);
    }

    /**
     * @param bool $insert
     * @return bool
     */
    function beforeSave($insert)
    {
        if(parent::beforeSave($insert)){
            if($insert){
                $this->create_time = time();
                $this->update_time = time();
                $this->reading = '1';
            }else{
                $this->update_time = time();
                $this->create_time = strtotime($this->create_time);
            }
            return true;
        }else{
            return fale;
        }
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStore()
    {
        return $this->hasOne(Store::className(), ['store_id' => 'store_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProperties()
    {
        return $this->hasMany(ProductProperty::className(), ['product_id' => 'product_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAccounts()
    {
        return $this->hasMany(UserAccount::className(), ['account_id' => 'account_id'])->viaTable('shopping_cart', ['product_id' => 'product_id']);
    }
}
