<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "product_basic".
 *
 * @property int $product_id （产品ID）
 * @property int $store_id （关联商店ID）
 * @property string $product_name （商品名称）
 * @property string $product_subhead （商品副标题）
 * @property string $product_taxonomy （产品分类）
 * @property int $brand_id （品牌ID）
 * @property string $market_price （市场价格，预留字段）
 * @property string $product_price （商品价格）
 * @property string $product_image （商品缩略图）
 * @property string $product_introduction （商品介绍）
 * @property int $product_quantity （库存量）
 * @property int $product_status （产品状态，1-上架，2-下架）
 * @property int $create_time （创建时间）
 * @property int $update_time （修改时间）
 */
class Product extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'product_basic';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['store_id', 'product_name', 'product_subhead', 'product_taxonomy', 'brand_id', 'market_price', 'product_price', 'product_image', 'product_introduction', 'product_quantity', 'product_status'], 'required'],
            [['create_time', 'update_time'], function($attr, $params) {
                if ($this->hasErrors()) return false;

                $datetime = $this->{$attr};

                $time = strtotime($datetime);
                // 验证时间格式是否正确
                if ($time === false) {
                    $this->addError($attr, '时间格式错误.');
                    return false;
                }
                // 将转换为时间戳后的时间赋值给time属性
                $this->{$attr} = $time;
                return true;
            }],
            [['store_id', 'brand_id', 'product_quantity', 'product_status'], 'integer'],
            [['market_price', 'product_price'], 'number'],
            [['product_name', 'product_subhead', 'product_taxonomy'], 'string', 'max' => 64],
            [['product_image'], 'string', 'max' => 300],
            [['product_introduction'], 'string', 'max' => 20000],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'product_id' => '序号',
            'store_id' => '商店',
            'product_name' => '标题',
            'product_subhead' => '副标题',
            'product_taxonomy' => '系列',
            'brand_id' => '品牌',
            'market_price' => '市场价',
            'product_price' => '当前价',
            'product_image' => '缩略图',
            'product_introduction' => '商品详情',
            'product_quantity' => '库存量',
            'product_status' => '状态',
            'create_time' => '提交时间',
            'update_time' => '修改时间',
        ];
    }

    function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        $this->create_time = date('Y-m-d H:i:s', $this->create_time);
        $this->update_time = date('Y-m-d H:i:s', $this->update_time);
    }

    function beforeSave($insert)
    {
        if(parent::beforeSave($insert)){
            if($insert){
                $this->create_time = time();
                $this->update_time = time();
            }else{
                $this->update_time = time();
            }
            return true;
        }else{
            return fale;
        }
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStore()
    {
        return $this->hasOne(Store::className(), ['store_id' => 'store_id']);
    }
}
